### ISSUE TITLE
Opening in new window

### ISSUE THREAD

**Issue by RangerMauve** [carloshfoliveira/project-switcher#4]
It'd be nice if there was an option to open the projects in a new window rather than replacing the current one.

**Comment by chocoelho** [comment]
Wouldn't that be the same behaviour as opening another folder through the file menu?

**Comment by RangerMauve** [comment]
Kind of. It'd be a lot faster since it's a single keyboard shortcut and a fuzzy matcher for the folder title.

**Comment by chocoelho** [comment]
Hmm, I'm gonna take a look at it and check what it takes to do that, but I've already got something in mind that may do the trick.

**Comment by RangerMauve** [comment]
Awesome, can't wait to see it. :D

**Comment by chocoelho** [comment]
So, I'm back to Atom and working on this package, I guess the best option we've got is to add an option so users may switch it's behavior(open in same window or open another one).

**Comment by RangerMauve** [comment]
Yeah, a simple switch would be best, I think.

**Comment by chocoelho** [comment]
I had started this a long ago, but had a problem with my machine back then, so I lost my code(forgot to push it, though I had prepared the commit). I'm back to Atom, did a few updates, now will started again, but using the new API :+1:

**Comment by RangerMauve** [comment]
:+1: Nice

**Comment by chocoelho** [comment]
@RangerMauve I've done it. Please update to v1.1.0

**Comment by RangerMauve** [comment]
@carloshfoliveira Works like a charm. Thanks!

**Comment by chocoelho** [comment]
Great! Feel free to suggest features you think may be useful and should be in this plugin :)
